### ISSUE TITLE
为啥每次需要联网download？

### ISSUE THREAD

**Issue by imfifc** [Cyberbolt/selenium-linux-server#2]

**Comment by imfifc** [comment]
![image](https://user-images.githubusercontent.com/53161431/211504385-d383da7b-158e-4606-bf63-a0bb835d9e35.png)

**Comment by Cyberbolt** [comment]
这是 Selenium 的问题？应该不是该镜像的问题。您也可以选择手动指定 Chrome 驱动的路径 /opt/google/chrome/chromedriver
