### ISSUE TITLE
请教一个精简docker镜像的问题

### ISSUE THREAD

**Issue by flyweb291** [Cyberbolt/selenium-linux-server#4]
以下是我精简镜像的过程，导致启动不了，虽然能得到500mb小镜像，但是无法正常运行报错raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")

# 第一阶段：安装 Chrome 和 ChromeDriver
FROM python:3.9-slim as build-stage

RUN apt-get update && apt-get install -y \
    wget \
    libatomic1 \
    gnupg2 \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && apt-get install -y chromium-driver \
    && rm -rf /var/lib/apt/lists/* \
    && rm google-chrome-stable_current_amd64.deb

# 第二阶段：构建最终镜像
FROM python:3.9-slim

# 复制 Chrome 和 ChromeDriver 到新镜像
COPY --from=build-stage /usr/bin/google-chrome /usr/bin/google-chrome
COPY --from=build-stage /usr/bin/chromedriver /usr/bin/chromedriver
COPY --from=build-stage /usr/lib/chromium /usr/lib/chromium

# 安装 Python 依赖
RUN pip install selenium

# 复制您的 Python 脚本
COPY JinJiaTyping.py /app/JinJiaTyping.py

WORKDIR /app
CMD ["python", "JinJiaTyping.py"]

**Comment by Cyberbolt** [comment]
参考这个方法搭建 Selenium 环境：https://www.cyberlight.xyz/passage/python3-selenium-linux
